config/routes.rb
Rails.application.routes.draw do
  resources :photos do 
    resources :comments
  end
  
  resources :articles do 
    resources :comments
  end
  
  resources :events do 
    resources :comments
  end
  
  resources :lotes
  resources :locations

end

app/models/lote.rb
class Lote < ActiveRecord::Base
end

app/controllers/lotes_controller.rb
class LotesController < ApplicationController
  before_action :set_lote, only: [:show, :edit, :update, :destroy]

  # GET /lotes
  # GET /lotes.json
  def index
    @lotes = Lote.all
  end

  # GET /lotes/1
  # GET /lotes/1.json
  def show
  end

  # GET /lotes/new
  def new
    @lote = Lote.new
  end

  # GET /lotes/1/edit
  def edit
  end

  # POST /lotes
  # POST /lotes.json
  def create
    @lote = Lote.new(lote_params)

    respond_to do |format|
      if @lote.save
        format.html { redirect_to @lote, notice: 'Lote was successfully created.' }
        format.json { render :show, status: :created, location: @lote }
      else
        format.html { render :new }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lotes/1
  # PATCH/PUT /lotes/1.json
  def update
    respond_to do |format|
      if @lote.update(lote_params)
        format.html { redirect_to @lote, notice: 'Lote was successfully updated.' }
        format.json { render :show, status: :ok, location: @lote }
      else
        format.html { render :edit }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotes/1
  # DELETE /lotes/1.json
  def destroy
    @lote.destroy
    respond_to do |format|
      format.html { redirect_to lotes_url, notice: 'Lote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lote
      @lote = Lote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lote_params
      params.require(:lote).permit(:nombre, :cordenadas, :area, :localidad)
    end
end

app/helpers/lotes_helper.rb
module LotesHelper
end

app/views/lotes/_form.html.erb
<%= form_for(@lote) do |f| %>
    <%= f.label :nombre %>
    <%= f.text_field :nombre %></br>
    <%= f.label :cordenadas %>
    <%= f.text_field :cordenadas %></br>
    <%= f.label :area %>
    <%= f.text_field :area %></br>
    <%= f.label :localidad %>
    <%= f.text_field :localidad %></br>

  <div id="map-canvas" class='columns small-12' style='height: 400px; width: 600px;'></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lotes/edit.html.erb
<h1>Editing Lote</h1>

<%= render 'form' %>

<%= link_to 'Show', @lote %> |
<%= link_to 'Back', lotes_path %>

app/views/lotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lotes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lotes.each do |lote| %>
      <tr>
        <td><%= lote.nombre %></td>
        <td><%= link_to 'Show', lote %></td>
        <td><%= link_to 'Edit', edit_lote_path(lote) %></td>
        <td><%= link_to 'Destroy', lote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lote', new_lote_path %>

app/views/lotes/new.html.erb
<h1>New Lote</h1>

<%= render 'form' %>

<%= link_to 'Back', lotes_path %>

app/views/lotes/show.html.erb
<strong>Nombre:</strong>
<%= @lote.nombre %>